pipeline {
    agent any
    environment {
        AWS_ACCOUNT_ID = credentials('aws-account-id')  // AWS Account ID
        AWS_REGION = credentials('aws-region')  // AWS Region
        ECR_REPO_NAME = 'admin-front'
        IMAGE_TAG = "${env.BUILD_NUMBER}"
        AWS_ACCESS_KEY_ID = credentials('aws-access-key-id')  // AWS Access Key ID
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')  // AWS Secret Access Key
        KUBECONFIG = credentials('kubeconfig')  // Kubernetes config file
        GIT_CREDENTIALS_ID = 'github-credentials'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/ghtjr410/eks-alb-ecr-docker-helm.git',
                    credentialsId: "${GIT_CREDENTIALS_ID}"
            }
        }
        stage('Build Docker Image') {
            when {
                changeset "admin-front/**"  // admin-front 디렉토리에 변경이 있는 경우에만 실행
            }
            steps {
                script {
                    docker.build("${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}", 'admin-front/.')
                }
            }
        }
        stage('Login to ECR') {
            when {
                changeset "admin-front/**"  // admin-front 디렉토리 변경이 있는 경우에만 실행
            }
            steps {
                script {
                    withEnv([
                        'AWS_ACCESS_KEY_ID=' + credentials('aws-access-key-id'),
                        'AWS_SECRET_ACCESS_KEY=' + credentials('aws-secret-access-key')
                    ]) {
                        bat 'aws ecr get-login-password --region %AWS_REGION% | docker login --username AWS --password-stdin %AWS_ACCOUNT_ID%.dkr.ecr.%AWS_REGION%.amazonaws.com'
                    }
                }
            }
        }
        stage('Push Docker Image to ECR') {
            when {
                changeset "admin-front/**"  // admin-front 디렉토리 변경이 있는 경우에만 실행
            }
            steps {
                script {
                    docker.image("${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${IMAGE_TAG}").push()
                }
            }
        }
        // stage('Deploy to EKS') {
        //     when {
        //         changeset "admin-front/**"  // admin-front 디렉토리 변경이 있는 경우에만 실행
        //     }
        //     steps {
        //         script {
        //             bat 'helm upgrade --install my-release ./helm-chart --set image.repository=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME},image.tag=${IMAGE_TAG}'
        //         }
        //     }
        // }
    }
}